BigInt
yevkk/bignum-arithmetic-eliptic-curves pull request #2
Opened 2019-10-20 08:13 UTC by aoyako

2019-10-20 08:16 UTC, aoyako commented
@ostapmk По какой-то причине я не могу добавить ревьюверов

2019-10-20 09:19 UTC, ostapmk requested changes

2019-10-20 09:19 UTC, ostapmk commented on Src/BigNum.hpp
> +// -*- lsst-c++ -*-
В цій шапці нема особливого сенсу

2019-10-20 09:19 UTC, ostapmk commented on Src/BigNum.hpp
>  #pragma once
Між інклуд гардом(у даному випадку `#pragma once`) й інклудами повинен бути пустий рядок

2019-10-20 09:19 UTC, ostapmk commented on Src/BigNum.hpp
> +    namespace big {
С++17 дозволяє писати конкатеновані неймспейси - `namespace lab::big`. Назва неймспейсу `big` трохи некоректна, ліпше назвати типу `numeric`. А ліпше взагалі ніякий неймспейс не додавати, бо буде тільки клас і декілька функцій, які вже й так в неймспейсі `lab`. І надалі інденшн класу/функцій повинен бути на рівні інденшина неймспейса
```cpp
namespace foo {

class bar {
...
};

} // namespace foo
```

2019-10-20 09:19 UTC, ostapmk commented on Src/BigNum.hpp
> +        /** NUM_BASE points to the max value BigNum array's cell can hold
Такі випадки коментуються наступним чином:

```cpp
/**
 * @brief Foo description
 *        ...
 */
const int foo = ...;

/**
 * @brief Bar description
 *        ...
 */
const int bar = ...;
```

2019-10-20 09:19 UTC, ostapmk commented on Src/BigNum.hpp
> +        const char SECTION_DIGITS = 9;
Тут очевидне порушення [ODR](https://en.wikipedia.org/wiki/One_Definition_Rule). Якщо оголошуєш константу в хедері, то до неї додавай `inline` специфікатор:
```cpp
const inline int foo = ...;
```

Також, ти присвоюєш константі літерал, а це значення часу компіляції, отже коректніше буде написати `constexpr`. 

Клієнту не потрібно знати ці константи, оскільки він просто хоче використати клас `BigInt`. Також, ці константи не використовуються в хедері, тому коректніше перемістити їх в .cpp

2019-10-20 09:19 UTC, ostapmk commented on Src/BigNum.hpp
> +        const int NUM_BASE = 1000000000;
Див попередній

2019-10-20 09:19 UTC, ostapmk commented on Src/BigNum.hpp
> +        /** @class
```cpp
/**
 * @brief ...
 */
```
Але якщо хочеш залишити тег `class`, то принаймні перемісти його на наступний рядок, перший рядок Doxygen комментів має бути порожнім

2019-10-20 09:19 UTC, ostapmk commented on Src/BigNum.hpp
> +         *
Зайвий рядок

2019-10-20 09:19 UTC, ostapmk commented on Src/BigNum.hpp
> +        private:
Організація класу повинна бути наступною:
* паблік підтипи
* паблік функції
* приватні функції
* приватні поля

Відповідно, `_digits` перемісти

2019-10-20 09:19 UTC, ostapmk commented on Src/BigNum.hpp
> +            BigNum(const BigNum& r);
Дефолтні речі зазвичай не коментують, але якщо ти все-таки анотуєш функцію, то використовуй загальний стиль
```
/**
 * @brief Copy constructor.
 */
```
Коменти поміняй у всіх відповідних місцях.

Також, у даному випадку у тебе конструктор копії. Очевидно, що там просто буде зкопійований вектор, нема сенсу його вручну писати, починаючи з С++11 компілятор може це зробити за тебе:
```cpp
BigNum(const Bignum& that) = default;
```

2019-10-20 09:19 UTC, ostapmk commented on Src/BigNum.hpp
> +            BigNum(std::string num);
`std::string` -> `std::string_view`
https://en.cppreference.com/w/cpp/string/basic_string_view

2019-10-20 09:19 UTC, ostapmk commented on Src/BigNum.hpp
> +            BigNum();
1) Коментарі мають бути однозначними без `DONT USE`, `?`. 
2) 
```cpp
BigNum() = default;
```

2019-10-20 09:19 UTC, ostapmk commented on Src/BigNum.hpp
> +            BigNum& operator=(const BigNum& r);
```cpp
BigNum& operator(const BigNum& that) = default;
```

2019-10-20 09:19 UTC, ostapmk commented on Src/BigNum.hpp
> +            std::string str();
```cpp
std::string str() const;
```
Але краще зробити френдову функцію `to_string`, яка приймає `BigNum` як параметр. Так не буде спроби порушити Single Responsibility Principle.

2019-10-20 09:19 UTC, ostapmk commented on Src/BigNum.hpp
> +             * !DO NOT USE THESE OPERATORS!
Вище писав з цього приводу

2019-10-20 09:19 UTC, ostapmk commented on Src/BigNum.hpp
> +            friend BigNum operator-(const BigNum& num1, const BigNum& num2);
```cpp
friend BigNum operator-(const BigNum& lhs, const BigNum& rhs);
```
`lhs` - left hand side, `rhs` відповідно. Також можна писати `left`/`right`.

2019-10-20 09:19 UTC, ostapmk commented on Src/BigNum.hpp
> +            friend std::ostream& operator<<(std::ostream& os, const BigNum& num);
Цю функцію краще зробити шаблонною 
```cpp
template<typename OStream>
friend OStream& operator<<(Ostream& os, const BigNum& num);
```
Так я зможу виводити число у якийсь кастомний потік(наприклад, в Qt свої кастомні реалізації потоків для дебагу і тому подібного), а не тільки в `ostream`.

2019-10-20 09:19 UTC, ostapmk commented on Src/BigNum.hpp
> +             * add function performs modulo addition
`@brief Function performs modulo addition.`

2019-10-20 09:19 UTC, ostapmk commented on Src/BigNum.hpp
> +            friend BigNum add(const BigNum& num1, const BigNum& num2, const BigNum& mod);
Параметри відповідно перейменувати на `first`/`second`. Поправити у всіх відповідних місцях

2019-10-20 09:19 UTC, ostapmk commented on Src/BigNum.hpp
> +             * @param num1 first BigNum
`@param first First number.`
Коменти в Doxygen мають бути докінченими реченнями, поправити у всіх відповідних місцях

2019-10-20 09:19 UTC, ostapmk commented on Src/BigNum.hpp
> +            /// Helper functions
Цей комент зайвий

2019-10-20 09:19 UTC, ostapmk commented on Src/BigNum.hpp
> +            int& operator[](int index);
Цей оператор нелогічний: ти ж не можеш звернутися по індексу до інтової змінної. Його краще прибрати

2019-10-20 09:19 UTC, ostapmk commented on Src/BigNum.hpp
> +            friend std::vector<char> toOneDigit(const BigNum& num1);
Хіба це не те саме, що `str()` тільки вертає чари у векторі?

2019-10-20 09:36 UTC, ostapmk commented
Буде більш інтуїтивно і легше знайти, якщо в назву пул реквеста виносити номер варіанту

2019-10-20 10:03 UTC, aoyako commented on Src/BigNum.hpp
> +             * !DO NOT USE THESE OPERATORS!
Як можна позначити, щоб інші не використовували?

2019-10-20 10:06 UTC, aoyako commented on Src/BigNum.hpp
> +            friend std::ostream& operator<<(std::ostream& os, const BigNum& num);
Аналогічно і для ` istream` ?

2019-10-20 10:12 UTC, aoyako commented on Src/BigNum.hpp
> +             * @param num1 first BigNum
Буде логічним залишити ` @param first/second` без опису, якщо функція примітивна?

2019-10-20 10:13 UTC, ostapmk commented on Src/BigNum.hpp
> +             * !DO NOT USE THESE OPERATORS!
Якщо їх інші не мають використовувати, то їх взагалі не треба тоді

2019-10-20 10:13 UTC, ostapmk commented on Src/BigNum.hpp
> +            friend std::ostream& operator<<(std::ostream& os, const BigNum& num);
Так

2019-10-20 10:14 UTC, ostapmk commented on Src/BigNum.hpp
> +             * @param num1 first BigNum
Так, без проблем

2019-10-20 10:37 UTC, aoyako commented on Src/BigNum.hpp
> +            friend std::ostream& operator<<(std::ostream& os, const BigNum& num);
Щоб запобігти ` undefined reference` для операторів, їх реалізацію переносити в .hpp файл?

2019-10-20 10:39 UTC, ostapmk commented on Src/BigNum.hpp
> +            friend std::ostream& operator<<(std::ostream& os, const BigNum& num);
Так, але їх дефінішн після оголошення класу, так званий out-of-line definition

2019-10-20 11:24 UTC, ostapmk requested changes

2019-10-20 11:24 UTC, ostapmk commented on Src/BigNum.hpp
> + * @brief BigNum class can hold big POSITIVE integers
Докінчені речення; нашо капсом виділяти? Це Doxygen, тут можна використовувати маркдаун: `BigNum class can hold big **positive** integers.`

2019-10-20 11:24 UTC, ostapmk commented on Src/BigNum.hpp
> +     * @brief operator- for subtracting two BigNums
Або окремий комент для оператор+, або всі операції одним коментом(включаючи *, /)

2019-10-20 11:24 UTC, ostapmk commented on Src/BigNum.hpp
> +     * @param num
Нема сенсу писати `@param <name>` , якщо параметри не потрібно описувати. З `@return` те саме. Просто залишати `@brief ...` тай усе. У відповідних місцях пофіксь. Сам побачиш, що так набагато простіше читається

2019-10-20 11:24 UTC, ostapmk commented on Src/BigNum.hpp
> +      * @brief toOneDigit function returns a vector of BigNum 's digits
В описі функції не потрібно використовувати назву функції; в зкомпільованому Doxygen'і контекст функції завжди відомий

2019-10-20 11:24 UTC, ostapmk commented on Src/BigNum.hpp
> +    for (int last_index = num._digits.size() - 1; last_index >= 0; last_index--) {
Можеш використати реверс ітератор вектора:
```cpp
for (auto it = num._digits.rbegin(); it != num._digits.rend(); ++it) {
    os << *it;
}
```
Читається просто супер: пройдемося по контейнеру в зворотньому порядку і виведемо кожен елемент в потік. Ніяких індексів, нічого зайвого

2019-10-20 11:29 UTC, aoyako commented on Src/BigNum.hpp
> +     * @brief operator- for subtracting two BigNums
Якщо тільки ` @note` важливий, прибирати ` @brief` ?

2019-10-20 11:33 UTC, ostapmk commented on Src/BigNum.hpp
> +     * @brief operator- for subtracting two BigNums
Так

2019-10-20 11:34 UTC, aoyako commented on Src/BigNum.hpp
> +      * @brief toOneDigit function returns a vector of BigNum 's digits
Слово ` function` в описі теж видаляти?

2019-10-20 11:59 UTC, ostapmk commented on Src/BigNum.hpp
> +      * @brief toOneDigit function returns a vector of BigNum 's digits
Тут взагалі буде ідеальним, по-моєму,
```cpp
/**
 * @brief Converts number to vector of its digits
 * @return Vector of digits
 */
```

2019-10-23 17:37 UTC, aoyako commented
@ostapmk Я виправив, що ти казав. Інші вже просять реалізацію, можеш мержити.

2019-10-23 19:11 UTC, ostapmk requested changes
Постарайся максимально спростити інтерфейс класу, щоб він буквально поводив себе як деяке число: вивід в потім, читання з потоку, перегружені оператори та де/сереалізація в стрінгу. Запевняю, що кількість коду зменшиться, а надійність та консистентність збільшиться

2019-10-23 19:11 UTC, ostapmk commented on Src/BigNum.cpp
> + * same as basis in linear representation
```
/**
 * @brief ...
 *        ...
 */

2019-10-23 19:11 UTC, ostapmk commented on Src/BigNum.cpp
> +constexpr int NUM_BASE = 1000000000;
Константи краще в анонімний неймспейс додати

2019-10-23 19:11 UTC, ostapmk commented on Src/BigNum.cpp
> +    _digits.clear();
В цьому нема сенсу

2019-10-23 19:11 UTC, ostapmk commented on Src/BigNum.cpp
> +    std::string result = "";
Зануляти стрінгу теж нема сенсу, тільки зайва алокація

2019-10-23 19:11 UTC, ostapmk commented on Src/BigNum.cpp
> +    for (int curr_pos = 0; curr_pos <num._digits.size() ; curr_pos++) {
Пробіл між операторами; постфіксний оператор краще не використовувати - зайва алокація на кожній ітерації

2019-10-23 19:11 UTC, ostapmk commented on Src/BigNum.cpp
> +            }else leading_zeros = 0;
Пробіл, брейси для блоку інструкцій, інструкції на новому рядку

2019-10-23 19:11 UTC, ostapmk commented on Src/BigNum.cpp
> +bool operator<(const BigNum &left, const BigNum &right) {
Для вектора є `operator<` і решта, краще вручну це не писати, а ліпше
```cpp
bool operator<(const BigNum& left, const BigNum& right) {
    /// Compare in reverse order
    return left._digits > right._digits;
}
```

2019-10-23 19:11 UTC, ostapmk commented on Src/BigNum.hpp
> +    std::vector<int> _digits; ///< Array of coefficients in representation
Комент зверху, а не в одному рядку

2019-10-23 19:11 UTC, ostapmk commented on Src/BigNum.hpp
> +    friend std::vector<char> toOneDigit(const BigNum& num);
Так і не зрозумів, нашо ця функція: `std::vector<char> ~ std::string`. По суті еквівалент `to_string`

2019-10-23 19:11 UTC, ostapmk commented on Src/BigNum.hpp
> +    friend BigNum toBigNum(std::vector<char>& num_digits);
Те саме, це ліпше замінити на
```cpp
friend BigNum from_string(std::string_view str);
```

2019-10-23 19:11 UTC, ostapmk commented on Src/BigNum.hpp
> +      * @brief Converts vector of digits to number
Дока на один спейс вліво з`їхала

2019-10-23 19:11 UTC, ostapmk commented on Tests/TestBigNum.cpp
> +            iss>>num;
Всюди не забувай про пробіли між операторами і операндами - читаємість коду

2019-10-23 19:11 UTC, ostapmk commented on Tests/TestBigNum.cpp
> +            std::string in = "000000000001234567890";
Не забувай про `const` всюди, де це має сенс

2019-10-23 19:11 UTC, ostapmk commented on Tests/TestBigNum.cpp
> +            REQUIRE(!(a < b));
Не той оператор

2019-10-23 19:11 UTC, ostapmk commented on Tests/TestBigNum.cpp
> +            REQUIRE(!(a < b));
Також не той оператор

2019-10-23 19:11 UTC, ostapmk commented on Src/BigNum.cpp
> +    std::vector<char> fnum = toOneDigit(left);
Купу раз вказуєш назву типу, краще `auto`, контекст і так зрозумілий

2019-10-23 19:11 UTC, ostapmk commented on Src/BigNum.hpp
> +    friend BigNum add(const BigNum& first, const BigNum& second, const BigNum& mod);
В цих функціях нема ніякого сенсу, краще реалізуй взяття числа по модулю -- зможеш писати `(a + b) % c` замість цієї функції, те саме з сабстрактом і екстрактом

2019-10-23 19:13 UTC, ostapmk commented
@aoyako Якщо маркаєш якісь функції як `TODO`, то краще їх сигнатури навіть не писати, бо получається неатомарний стан проекту: є якісь функції, але вони не реалізовані. В стабільній бранчі(мастері) завжди має бути тільки консистентний код

2019-10-23 19:19 UTC, aoyako commented on Src/BigNum.cpp
> + * same as basis in linear representation
Не зрозумів, tab перед 3ю строкою поставити?

2019-10-23 19:25 UTC, aoyako commented on Src/BigNum.cpp
> +    _digits.clear();
Я роблю ` push_back()` , тому вектор повинен бути порожнім

2019-10-23 19:28 UTC, ostapmk commented on Src/BigNum.cpp
> +    _digits.clear();
Конструктор `BigNum` викликає дефолтний конструктор вектора, якщо не вказано інакше. Дефолтний конструктор веткора конструює його пустим

2019-10-23 19:29 UTC, ostapmk commented on Src/BigNum.cpp
> + * same as basis in linear representation
В сьомому рядку текст має бути на рівні тексту з попереднього рядка, а у тебе він на рівні тегу

2019-10-23 19:43 UTC, aoyako commented on Src/BigNum.hpp
> +    friend std::vector<char> toOneDigit(const BigNum& num);
В принципі еквівалентні, але з векторами мені зрозуміліше, ніж зі строками. Надалі функції переводу з числа у вектор і навпаки будуть видалені, коли я напишу покращене ділення в стовпчик (це вже буде після варіанту Іллі).

2019-10-23 19:45 UTC, ostapmk commented
Та майже напевно зручніше, але тут питання логіки й інтерфейсу

2019-10-23 19:46 UTC, aoyako commented on Src/BigNum.hpp
> +    friend BigNum toBigNum(std::vector<char>& num_digits);
Додав нову функцію, щодо старої - дивись попередню відповідь

2019-10-23 19:58 UTC, aoyako commented on Tests/TestBigNum.cpp
> +            REQUIRE(!(a < b));
Перевіряє оператор < для рівних чисел, очікувана відповідь ` false`

2019-10-23 19:59 UTC, aoyako commented on Tests/TestBigNum.cpp
> +            REQUIRE(!(a < b));
Перевіряє оператор < для числа строго меншого, очікувана відповідь false

2019-10-23 20:02 UTC, aoyako commented on Src/BigNum.hpp
> +    friend BigNum add(const BigNum& first, const BigNum& second, const BigNum& mod);
Для від'ємного результату віднімання треба перебудовувати класс для знаку '-'. Так само вирішив змінити для '+'

2019-10-23 20:05 UTC, aoyako commented on Src/BigNum.cpp
> +bool operator<(const BigNum &left, const BigNum &right) {
Ця штука не хоче працювати. (Зациклюється)

2019-10-24 20:36 UTC, ostapmk commented on Src/BigNum.cpp
> +bool operator<(const BigNum &left, const BigNum &right) {
Так, тут я трохи протупив. В С++20 завезуть `std::span` і це буде виглядати капельку по-іншому:
```cpp
return std::span{left._digits.rbegin(), relf._digits.rend()} < std::span{/*same for right*/};
```

2019-10-24 20:39 UTC, ostapmk commented on Tests/TestBigNum.cpp
> +        std::istream input();
Ніде не використовується, ще й оголошено як функцію

2019-10-24 20:40 UTC, ostapmk commented on Tests/TestBigNum.cpp
> +    /// Other operators use '<', no need to check them
Комент видно не дійшов -- треба всі оператори тестити

2019-10-24 20:45 UTC, ostapmk requested changes
Коли ще ці відкоментовані зміни зробиш -- пройдися сам по коду і поправ всюди форматування, бло місцями нереально читати:
1. Кожен блок в іф/елс повинен бути загорнутий в брейси
2. Пробіли між всіма операторами і операндами
3. Не ставити пробіл перед викликом конструктора
4. `i++` -> `++i`

Після всіх змін я ще рез перегляну код

2019-10-24 20:45 UTC, ostapmk commented on Src/BigNum.cpp
> +        long long counter = 0;
1. Нашо лонг лонг, якщо у векторі зберігаються інти?
2. `_digits.push_back(std::stoi(curr_section))` замість циклу вручну

2019-10-24 20:50 UTC, aoyako commented on Src/BigNum.cpp
> +        long long counter = 0;
https://stackoverflow.com/questions/16826422/c-most-efficient-way-to-convert-string-to-int-faster-than-atoi . Але якщо треба, заміню

2019-10-24 21:19 UTC, ostapmk commented on Src/BigNum.cpp
> +        long long counter = 0;
Тут згідний, але якщо підохидити з такої точки зору перфомансу, то прав всі місця, де робиш купу некорисних аллокацій(в тому числі сабстракт стрінги можна замінити на виділення її через стрінг в'ю, щоб не робити мільйон непотріьних алокацій, які собою перекривають недостатки `stoi`), таких місць купа. Але якщо ти не будеш це робити, то краще заміни на `std::stoi` -- так хоть читатись буде простіше.

2019-10-25 16:59 UTC, aoyako commented
На ` auto` не буду міняти, так прозоріше.

2019-10-25 17:18 UTC, ostapmk commented
Нехай. Після реалізації ділення, мусиш видалити непотрібні функції з інтерфейсу класу.

2019-10-25 17:19 UTC, merged