final
yevkk/bignum-arithmetic-eliptic-curves pull request #4
Opened 2019-11-23 11:35 UTC by starquell

modulo multiplication && inverted number && udl for bignum

2019-11-23 21:39 UTC, ostapmk commented
Назва PR багатослівна і однозначна

2019-11-23 21:48 UTC, starquell commented
> Назва PR багатослівна і однозначна

2019-11-23 22:18 UTC, ostapmk requested changes
Ще купу місць не відмічав, але в багатьох місцях потрібно правильно код форматувати

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.cpp
> +        else {
Форматування нашо змінив?

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.cpp
>          result._digits.push_back(addition);
Форматування: 
```cpp
if (...) {
    ...
} else {
    ...
}
```

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.cpp
> +    else {
Форматування

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.cpp
> +
Зайвий рядок

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.cpp
> +
Зайвий рядок

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.cpp
> +
Зайвий рядок

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.cpp
> +        const Iter begin () const {
Забери всюди пробіл після імені функції, притримуйся загального стилю

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.cpp
> +    class VectorView {
Клас реалізований не найкращим чином, ти міг зробити його простішим і очевиднішим, до того ж він міг би працювати з елементами будь-яких типів. Сенс називати клас `VectorView` і параметризувати його параметризованим ітератором?

По-моєму, кращим рішенням буде:
```cpp
template<typename T>
class ArrayView
{
public:
    template<typename Iter>
    ArrayView(Iter begin, Iter end) noexcept :
    ...

private:
    const T* array;
    std::size_t size;
}
```

Відповідно все буде працювати логічніше і очевидніше

```cpp
void foo(ArrayView<int> view);

...

const std::vector<int> v = {1, 2, 3};
foo(v);
```

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.cpp
> +
Зайвий рядок

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.cpp
> +
Зайвий рядок

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.cpp
> +        for (auto i = 0; i < length; ++i)
Потрібно врапити блок в брейси:
```cpp
for (...) {
    ...
}
```

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.cpp
> +
Пробіл

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.cpp
> +//namespace {
Якщо цей код закоментований, то його логічніше вирізати і не залишати тут

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.cpp
> +namespace {
Об'єднай все в один анонімний неймспейс, не логічно розділяти їх в декілька. Анонімний неймспейс практично те саме, що й звичайний

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.cpp
> +        if (b == BigNum("0"))
Брейси

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.cpp
> +        auto [int_part, remainder] = extract(a, b);
Const qualifiers
```cpp
const auto var = ...;
```

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.cpp
> +        return std::make_pair(y, subtract(x, (int_part * y) % mod, mod));
В С++17 можна писати `std::pair(...)`, для цього типу є дедакшн гайдс

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.cpp
> +        if (lhs == BigNum("0"))
Брейси

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.hpp
> +//
Закоментоване вирізай

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.hpp
> +    /**
Форматуванн

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.hpp
> +    //  enum ModuleMultiplicationPolicy {PreModule, PostModule};  //TODO
Прибрати

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.hpp
> +    /*
```
/**
 * @...
 */
```

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.hpp
> +    /*
Форматування, див попереднє

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.hpp
> +    /*
Форматування

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.hpp
> +}// namespace lab
Пробіл

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.hpp
> +lab::BigNum operator"" _bn(const char* str);
Зайвий пробіл

2019-11-23 22:18 UTC, ostapmk commented on Tests/TestBigNum.cpp
> +
Зайвий рядок

2019-11-23 22:18 UTC, ostapmk commented on Tests/TestBigNum.cpp
> +            REQUIRE(a * b == lab::BigNum("1010010203040505096969144002304102964934745672431934438795543769602041311552198728885697776938386026694281996784271367735387706565055641253207902666918261682
У таких великих числах нема абсолютно ніякого сенсу, старайся писати менші числа й більш наглядні, які не нагружають своїм розміром і не збільшують час виконання тестів своїм розміром

2019-11-23 22:18 UTC, ostapmk commented on Tests/TestBigNum.cpp
> +            const lab::BigNum a("99999123456789098765432112345678909876543219999");
Якщо написав UDL, то вже використовуй його

2019-11-23 22:18 UTC, ostapmk commented on Tests/main.cpp
>  #include "catch.hpp"
Додай перехід на новий рядок, навіщо ти його видалив?

2019-11-23 22:18 UTC, ostapmk commented on Tests/TestBigNum.cpp
> +
Зайвий рядок

2019-11-23 22:18 UTC, ostapmk commented on Tests/TestBigNum.cpp
>  #include <BigNum.hpp>
Додай порожній рядок між цими двома хедерами

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.hpp
> +    enum class InversionPolicy {Euclid, Fermat};
```cpp
enum class Name {
    v1,
    v2,
    ...
};
```

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.cpp
> +        auto c1 = karatsuba(lhsL, rhsL);
```cpp
const auto c1 = ...;
const auto c2 = ...;
const auto c3 = ...;
```

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.cpp
> +        else {
Форматування

2019-11-23 22:18 UTC, ostapmk commented on Src/BigNum.hpp
> +        std::string s(std::to_string(*it));
Купа зайвих операцій/алокацій, якщо не враховувати SBO.
Кращим варіантом буде:
```cpp
for (...) {
    char res[9];
    std::sprintf(res, "%09d", *it);
   
    os << res;
}
```

2019-11-23 22:22 UTC, starquell commented on Src/BigNum.cpp
> +namespace {
реалізацію функції кидаю в неймспейс після неї заради читабельності

2019-11-23 22:26 UTC, starquell commented on Src/BigNum.cpp
> +    class VectorView {
навіщо працювати класу з декількома типами і контейнерами, якщо він використовується в анонімному неймспейсі для реалізації одного алгоритму?

2019-11-23 22:26 UTC, starquell commented on Src/BigNum.cpp
> +    class VectorView {
навіщо працювати класу з декількома типами і контейнерами, якщо він використовується в анонімному неймспейсі для реалізації одного алгоритму?

2019-11-24 10:55 UTC, starquell commented on Src/BigNum.hpp
> +        std::string s(std::to_string(*it));
це частина @aoyako, я пофіксив, щоб працювати можливо було

2019-11-24 12:10 UTC, merged